name: Library

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        browser: [firefox, edge, chrome]

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup python 3.9
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
          architecture: 'x64'
          
      - name: Install Depencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r example/requirements.txt
          python -m pip freeze

      - name: Setup Browser
        uses: browser-actions/setup-${{ matrix.browser }}@latest

      - name: Run test
        run: |
          robot -d results .
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: results-${{ matrix.os }}-${{ matrix.browser }}
          path: /results
        
              
